port: 8070

server:
  port: ${port}

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:payment-service
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  flutter-config:
    public-key: ${PUB_KEY}
    secret-key: ${SECRET_KEY}
    init-url: https://api.flutterwave.com/v3/payments
    verify-url: https://api.flutterwave.com/v3/transactions
    redirect-url: http://localhost:${port}/api/payment/make-payment
